import Head from 'next/head'

import { Header, Main, Footer } from "../components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hello Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Main textContent='This is home page and default page' />

      <Footer />
    </>
  )
}
